# Numpy Array Operations

In [1]:
import numpy as np

#np arrays is a multidimensional array and better than using list to store large data
square_arr = np.array([1,2,9,16,25])

#zeros func create 5 elements with 0 values
zeros_arr = np.zeros(5)
# print(zeros_arr)

# arange func works like range has similar inputs fields
# arange_arr = np.arange(5)
# print(arange_arr)

newrange_arr = np.arange(0,9,2)
print(newrange_arr)

# random.rand an array on 10 random numbers between 0 to 1
rand_arr = np.random.rand(10)
print(rand_arr)

# create an empty array of length 5
empty_arr = np.empty(5)
print(empty_arr)

# dtype returns type
# print(empty_arr.dtype)

[0 2 4 6 8]
[0.57457495 0.5152656  0.78485555 0.52254953 0.04159169 0.27771037
 0.97542022 0.35583744 0.38682209 0.41095321]
[3.44900369e-307 3.22646744e-307 1.05695422e-307 1.44635488e-307
 1.37962320e-306]


# 2D AND 3D ARRAY OPERATIONS

In [2]:
oned_arr = np.array([
    1,3,9,10
])

# returns index value elements
oned_arr[1] 

#returns value between index 2 to last one
oned_arr[2:] 

twod_arr = np.array(
    [
        [1, 13, 5, 7], 
        [19, 11, 13, 15],
        [12, 4, 6, 8]
    ]
)

#returns row wise index value for n dimensions
# twod_arr[1,0]

#returns dimensions of array
# twod_arr.ndim

#replacing value in 2d array
# twod_arr[1,2] = 44

#returns slicing from 2nd index
# twod_arr[2:]

threed_arr = np.array(
    [
        [
            [1, 2, 3, 4], 
            [5, 6, 7, 8], 
            [9, 10, 11, 12]
        ],      
        [
            [13, 14, 15, 16], 
            [17, 18, 19, 20], 
            [21, 22, 23, 24]
        ]
    ]
)

#returns 1st element of 1st index of 3d array
# threed_arr[1,1,0]

#returns slicing
# threed_arr[1:]

#returns shape
# threed_arr.shape

#slicing sub array
threed_arr[1:]

array([[[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

# RESHAPE AND TRANSPOSE

In [23]:
#reshaping 1d to 2d array with 4 rows and 1 column note: all values should be matched by multiplication of arr (rows* cols)
# twod_arr_reshaped = np.reshape(oned_arr, (4,1)) 
twod_arr_reshaped = np.reshape(oned_arr, (2,2)) 
print("2D Reshaped: ",twod_arr_reshaped)

#flatten 2d and 3d array to 1d array using -1 
oned_arr_reshape = np.reshape(twod_arr, -1)
# oned_arr_reshape = np.reshape(threed_arr, -1)
# oned_arr_reshape

#transpose method opr
transposed_arr = np.transpose(twod_arr_reshaped)
print("2D Transpose Arr: ",transposed_arr)

2D Reshaped:  [[ 1  3]
 [ 9 10]]
2D Transpose Arr:  [[ 1  9]
 [ 3 10]]


# NUMERICAL OPERATIONS

In [21]:
#sum, subtract, multi, mod opr
arr1= np.array([1,4,5,6])
arr2= np.array([2,4,10,2])

# sum1d_arr = np.add(arr1,arr2)

# diff1d_arr = np.subtract(arr1,arr2)

# multi1d_arr = np.multiply(arr1, arr2)

# div1d_arr = np.divide(arr1, arr2)

# pow1d_arr = np.power(arr1, arr2)

mod1d_arr = np.mod(arr1, arr2)

# sum1d_arr
# diff1d_arr
# multi1d_arr
# pow1d_arr
mod1d_arr

array([1, 0, 5, 0])

# COMPARISON OPERATIONS

In [29]:
#comparison relation operations
print("Arr 1:",arr1) 
print("Arr 2:",arr2) 

# res = arr1 < arr2
res = np.less(arr1, arr2)
print("Less Than",res)

# res = arr1 > arr2
res = np.greater(arr1, arr2)
print("Greater Than",res)

# res = arr1 == arr2
res = np.equal(arr1, arr2)
print("Equal To",res)

# res = arr1 >= arr2
res = np.greater_equal(arr1, arr2)
print("Greater Than Equal To",res)

# res = arr1 <= arr2
res = np.less_equal(arr1, arr2)
print("Less Than Equal To",res)

# res = arr1 != arr2
res = np.not_equal(arr1, arr2)
print("Not Equal To",res)

Arr 1: [1 4 5 6]
Arr 2: [ 2  4 10  2]
Less Than [ True False  True False]
Greater Than [False False False  True]
Equal To [False  True False False]
Greater Than Equal To [False  True False  True]
Less Than Equal To [ True  True  True False]
Not Equal To [ True False  True  True]


# MEAN AND MEDIAN OPERATIONS WITH AXIS

In [70]:
#mean median min max operations
print("Arr 1:",arr1)

#returns sum of all elements / no of elements = mean
mean_val = np.mean(arr1)
print("Mean:",mean_val)

#returns middle value
median_val = np.median(arr1)
print("Median:",median_val)

#returns min, max
print("Min:",np.min(arr1))
print("Max:",np.max(arr1))

stud_marks = [50, 90, 80, 85, 57]
print("25 percentile marks: ", np.percentile(stud_marks,25))


Arr 1: [1 4 5 6]
Mean: 4.0
Median: 4.5
Min: 1
Max: 6
25 percentile marks:  57.0


In [38]:
# create a 2D array
array1 = np.array([[2, 14, 6], 
                   [18, 10, 12], 
                   [14, 16, 18]])

# median along horizontal axis e.g. [2, 6,14] row wise workds from left to right approach
result1 = np.median(array1, axis=1)
print("Median along horizontal axis :", result1)

# median along vertical axis e.g. [2,14,18] column wise works from top to bottom approach
result2 = np.median(array1, axis=0)
print("Median along vertical axis:", result2)

# compute median of entire array
result3 = np.median(array1)
print("Median of entire array:", result3)

# mean along horizontal axis e.g. [2, 6,14] row wise workds from left to right approach
result1 = np.mean(array1, axis=1)
print("Mean along horizontal axis :", result1)

# mean along vertical axis e.g. [2,14,18] column wise works from top to bottom approach
result2 = np.mean(array1, axis=0)
print("Mean along vertical axis:", result2)

# compute mean of entire array
result3 = np.mean(array1)
print("Mean of entire array:", result3)


Median along horizontal axis : [ 6. 12. 16.]
Median along vertical axis: [14. 14. 12.]
Median of entire array: 14.0
Mean along horizontal axis : [ 7.33333333 13.33333333 16.        ]
Mean along vertical axis: [11.33333333 13.33333333 12.        ]
Mean of entire array: 12.222222222222221


# STRING OPERATIONS

In [55]:
# add()	concatenates two strings
# multiply()	repeats a string for a specified number of times
# capitalize()	capitalizes the first letter of a string
# lower()	converts all uppercase characters in a string to lowercase
# upper()	converts all lowercase characters in a string to uppercase
# join()	joins a sequence of strings
# equal()	checks if two strings are equal or not

str_arr1 = np.array(['hero ','villian '])
str_arr2 = np.array(['batman', 'joker'])

print("Concat Res: ", np.char.add(str_arr1, str_arr2))

print("Multi Res:", np.char.multiply(str_arr1, 2))

print("Capitalise Res:", np.char.capitalize(str_arr1))

print("Upper Res:", np.char.upper(str_arr1))

print("Lower Res:", np.char.lower(str_arr1))

print("Join Res:", np.char.join('-',str_arr1))

Concat Res:  ['hero batman' 'villian joker']
Multi Res: ['hero hero ' 'villian villian ']
Capitalise Res: ['Hero ' 'Villian ']
Upper Res: ['HERO ' 'VILLIAN ']
Lower Res: ['hero ' 'villian ']
Join Res: ['h-e-r-o- ' 'v-i-l-l-i-a-n- ']


# MATRIX OPERATIONS IN ARRAY

In [65]:
# create two matrices
matrix1 = np.array([[2, 10], 
             		[15, 12]])
             
matrix2 = np.array([[2, 16], 
                    [4, 8]])

# calculate the dot product of the two matrices
result = np.dot(matrix1, matrix2)
print(result)

# calculate the multiply product of the two matrices
result = np.multiply(matrix1, matrix2)
print(result)

mat_3 = np.array(
    [
        [1, 5, 6],
        [2,4,9],
        [10,21,10]
    ]
)

print("Matrix:", mat_3)
print("Inverse of matrix:", np.linalg.inv(mat_3))
# det(A) = ad - bc
print("Determinant of matrix:", np.linalg.det(mat_3))
# converts 3d,2d into 1d array
print("Flatten of matrix:", mat_3.flatten())

[[ 44 112]
 [ 78 336]]
Matrix: [[ 1  5  6]
 [ 2  4  9]
 [10 21 10]]
Inverse of matrix: [[-0.69953052  0.35680751  0.09859155]
 [ 0.3286385  -0.23474178  0.01408451]
 [ 0.00938967  0.13615023 -0.02816901]]
Determinant of matrix: 213.00000000000009
Flatten of matrix: [ 1  5  6  2  4  9 10 21 10]


# SET OPERATIONS

In [69]:
A = np.array([1, 3, 5])
B = np.array([0, 2, 3])

# union of two arrays
result = np.union1d(A, B)
print("Union: ",result)
print("Intersection: ",np.intersect1d(A,B))
print("Set Diff: ",np.setdiff1d(A,B))
print("Set Symmetric Diff: ",np.setxor1d(A,B))
print("Unique: ",np.unique(A))

Union:  [0 1 2 3 5]
Intersection:  [3]
Set Diff:  [1 5]
Set Symmetric Diff:  [0 1 2 5]


# BOOLEAN INDEXING

In [72]:
res1 = np.array([[1, 7, 9], 
                    [14, 19, 21], 
                    [25, 29, 35]])

# create a boolean mask based on the condition 
# that elements are greater than 9
boolean_mask = res1 > 9

# select only the elements that satisfy the condition
result = res1[boolean_mask]

print(result)

[14 19 21 25 29 35]
