NumPy Exercises
1. Create and Manipulate Arrays
Create a 1D NumPy array of integers from 10 to 50.
Convert it into a 2D array of shape (5, 2).
Find the mean, sum, and standard deviation of the array.
2. Indexing and Slicing
Create a 5x5 array of random integers between 1 and 100.
Extract all values greater than 50.
Replace all values less than 30 with -1.
Extract the third row and second column.
3. Mathematical Operations
Create two (3x3) matrices with random values.
Perform matrix addition, subtraction, multiplication, and dot product.
Find the inverse of one matrix.
4. Filtering
Create an array of 20 random numbers between 1 and 100.
Find all even numbers and replace them with 0.
Normalize the array so that all values are between 0 and 1.

# Task 1

In [11]:
import numpy as np

arr1 = np.array([10,11,20,25,30,40,45,47,48,50])

newarr1 = np.reshape(arr1, (5,2))
print(newarr1)

print(np.mean(newarr1))
print(np.median(newarr1))
print(np.sum(newarr1))
print(np.std(newarr1))

[[10 11]
 [20 25]
 [30 40]
 [45 47]
 [48 50]]
32.6
35.0
326
14.6846859006245


# Task 2

In [26]:
rand_arr = np.random.randint(100, size=(5,5))
print(rand_arr)

rand_arr.shape

new_rand_arr = rand_arr[rand_arr > 50]

rand_arr[rand_arr < 30] = -1
rand_arr

rand_arr[3][2]

[[73 30 56 18 68]
 [10 44 23 55 41]
 [49 32 98  6 62]
 [27 15 37  7 22]
 [78 58 69 54 99]]


37

# Task 3

In [40]:
arr2 = np.random.randint(10, size=(3,3))
print(arr2)

arr3 = np.random.randint(10, size=(3,3))
print(arr3)

print("Add Matrix: \n", np.add(arr2, arr3))
print("Sub Matrix: \n", np.subtract(arr2, arr3))
print("Mul Matrix: \n", np.multiply(arr2, arr3))
print("Div Matrix: \n", np.divide(arr2, arr3))
print("Dot Matrix: \n", np.dot(arr2, arr3))
print("Inverse Matrix: \n", np.linalg.inv(arr2))

[[5 7 8]
 [8 7 9]
 [3 0 6]]
[[2 4 4]
 [1 3 3]
 [0 5 8]]
Add Matrix: 
 [[ 7 11 12]
 [ 9 10 12]
 [ 3  5 14]]
Sub Matrix: 
 [[ 3  3  4]
 [ 7  4  6]
 [ 3 -5 -2]]
Mul Matrix: 
 [[10 28 32]
 [ 8 21 27]
 [ 0  0 48]]
Div Matrix: 
 [[2.5        1.75       2.        ]
 [8.         2.33333333 3.        ]
 [       inf 0.         0.75      ]]
Dot Matrix: 
 [[ 17  81 105]
 [ 23  98 125]
 [  6  42  60]]
Inverse Matrix: 
 [[-0.4         0.4        -0.06666667]
 [ 0.2        -0.05714286 -0.18095238]
 [ 0.2        -0.2         0.2       ]]


C:\Users\Admin\AppData\Local\Temp\ipykernel_22908\3624496841.py:10: RuntimeWarning: divide by zero encountered in divide
  print("Div Matrix: \n", np.divide(arr2, arr3))


# Task 4

In [48]:
arr4 = np.random.randint(100, size=(20))
print(arr4)

#filtering no by replacing it with 0
arr4[arr4 % 2 == 0] = 0
arr4

[ 8 32  0 16  0 65 28 42 79 72 55 23 95 97 94 22 78 80 22 98]


array([ 0,  0,  0,  0,  0, 65,  0,  0, 79,  0, 55, 23, 95, 97,  0,  0,  0,
        0,  0,  0])

Pandas Exercises
1. Create and Explore a DataFrame
Create a DataFrame from a dictionary with columns: Name, Age, Salary, Department.
Add a new column "Bonus" that is 10% of the salary.
Find the average age and salary.
2. Handling Missing Data
Create a DataFrame with some NaN (missing) values.
Fill missing values using mean or median.
Drop rows where more than 2 values are missing.
3. Data Selection and Filtering
Load the "Titanic dataset" (sns.load_dataset('titanic')).
Select all passengers above 30 years old.
Find the number of survivors by gender.
Find the oldest passenger and their class.
4. Grouping and Aggregation
Create a DataFrame with Employee, Department, and Salary.
Group by Department and find the average salary.
5. Data Merging and Joining
Create two DataFrames:
One with Employee_ID and Name.
Another with Employee_ID and Salary.
Merge them based on Employee_ID.
Add a new column Tax as 15% of salary.
6. Time Series Data
Create a date range of the last 30 days.
Generate a random dataset with a "Sales" column.
Find the total sales for the last 7 days.
Plot the sales trend over time.

# Task 1

In [63]:
import pandas as pd

data = {
    "Name": ["Abby", "Ellie", "Joel"],
    "Age": [20,21,34],
    "Salary": [55000, 30000, 40000],
    "Department": ["IT", "HR", "QA"]
}

df = pd.DataFrame(data)
df

df["Bonus"] = df["Salary"] / 10
df

avg_sal = df["Salary"].mean()
avg_sal

avg_age = df["Age"].mean()
avg_age

25.0

# Task 2

In [74]:
data2 = {
    "Name": ["Abby", "Ellie", "Joel"],
    "Age": [20,None,34],
    "Salary": [None, 30000, None],
    "Department": ["IT", "HR", "QA"]
}

df2 = pd.DataFrame(data2)
df2

df2.fillna(df2["Age"].mean(), inplace=True)
df2

df2.fillna(df2["Salary"].median(), inplace=True)
df2

df2.loc[4] = ["Tess", None, None, None]
df2

df2.drop(index=4, inplace=True)
df2

C:\Users\Admin\AppData\Local\Temp\ipykernel_22908\4173336533.py:17: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df2.loc[4] = ["Tess", None, None, None]


Name   Age   Salary Department
0   Abby  20.0     27.0         IT
1  Ellie  27.0  30000.0         HR
2   Joel  34.0     27.0         QA

# Task 3

In [88]:
import seaborn as sns

df = sns.load_dataset('titanic')
df

df = df[df["age"] > 30]
df

gender = df[df["sex"] == "male"]
gender

oldest_pass = df[df["age"] == df["age"].max()]
oldest_pass

survived  pclass   sex   age  sibsp  parch  fare embarked  class  who  \
630         1       1  male  80.0      0      0  30.0        S  First  man   

     adult_male deck  embark_town alive  alone  
630        True    A  Southampton   yes   True

# Task 4

In [104]:
df2.fillna(df2["Age"].mean(), inplace=True)
df2

new_ddf = df2.groupby('Department')['Salary'].mean()
print(new_ddf)

Department
HR    30000.0
IT       27.0
QA       27.0
Name: Salary, dtype: float64


# Task 5

In [110]:
d1 = pd.DataFrame({"Emp_ID": [1,2,3] , "Name": ["Arun", "Varun", "Tarun"]})
d2 = pd.DataFrame({"Emp_ID": [1,2,3] , "Emp_Sal": [20000,30000,40000]})

df_merge = pd.merge(d1, d2, on="Emp_ID", how="inner")
df_merge

df_merge["Tax"] = df_merge["Emp_Sal"] / 15
df_merge

Emp_ID   Name  Emp_Sal          Tax
0       1   Arun    20000  1333.333333
1       2  Varun    30000  2000.000000
2       3  Tarun    40000  2666.666667

# Task 6

In [114]:
# Time Series Data Create a date range of the last 30 days. Generate a random dataset with a "Sales" column. Find the total sales for the last 7 days. Plot the sales trend over time.
date_range = pd.date_range(end=pd.Timestamp.today(), periods=30)
date_range

DatetimeIndex(['2025-01-15 15:51:11.219029', '2025-01-16 15:51:11.219029',
               '2025-01-17 15:51:11.219029', '2025-01-18 15:51:11.219029',
               '2025-01-19 15:51:11.219029', '2025-01-20 15:51:11.219029',
               '2025-01-21 15:51:11.219029', '2025-01-22 15:51:11.219029',
               '2025-01-23 15:51:11.219029', '2025-01-24 15:51:11.219029',
               '2025-01-25 15:51:11.219029', '2025-01-26 15:51:11.219029',
               '2025-01-27 15:51:11.219029', '2025-01-28 15:51:11.219029',
               '2025-01-29 15:51:11.219029', '2025-01-30 15:51:11.219029',
               '2025-01-31 15:51:11.219029', '2025-02-01 15:51:11.219029',
               '2025-02-02 15:51:11.219029', '2025-02-03 15:51:11.219029',
               '2025-02-04 15:51:11.219029', '2025-02-05 15:51:11.219029',
               '2025-02-06 15:51:11.219029', '2025-02-07 15:51:11.219029',
               '2025-02-08 15:51:11.219029', '2025-02-09 15:51:11.219029',
               '2025-02-1